version: "3"
services:
  deap:
    container_name: deap
    image: deap:1.0
    build:
      context: ./docker
      dockerfile: ./deap/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
